# Generated by Django 3.0.5 on 2020-04-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=64, verbose_name='Summary')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('date_created', models.DateField(auto_now=True)),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(verbose_name='End')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=32, verbose_name='Priority')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=32, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Member since')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=64, verbose_name='Summary')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('target_resolution_date', models.DateField(verbose_name='Target resolution date')),
                ('actual_resolution_date', models.DateField(verbose_name='Actual resolution date')),
                ('progress', models.CharField(max_length=255, verbose_name='Progress')),
                ('resolution_summary', models.CharField(max_length=1024, verbose_name='Resolution summary')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Assignee', to='api.User')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Author', to='api.User')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TaskPriority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TaskStatus')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
    ]
