# Generated by Django 3.0.5 on 2020-04-03 12:56

from django.db import migrations, transaction


def create_data(apps, schema_editor):
    with transaction.atomic():
        User = apps.get_model("api", "User")
        Project = apps.get_model("api", "Project")
        Task = apps.get_model("api", "Task")
        Priority = apps.get_model("api", "TaskPriority")
        Status = apps.get_model("api", "TaskStatus")
        status = Status(state="Doing")
        prio = Priority(priority="high")
        user = User(first_name="Julius", last_name="Taylor")
        project = Project(
            summary="Test project", author=user, start="2020-01-01", end="2020-01-01"
        )
        task = Task(
            summary="Task summary",
            author=user,
            project=project,
            target_resolution_date="2020-01-01",
            actual_resolution_date="2020-01-01",
            assignee=user,
            priority=prio,
            status=status,
        )
        status.save()
        prio.save()
        user.save()
        project.save()
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_data)]
