# Generated by Django 3.0.5 on 2020-04-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='state',
            new_name='status',
        ),
    ]
